keypress, click events for controller.js, made test function on mode…
nss-day-cohort-16/d16-gp-movie-history-team-scrappy pull request #5
Opened 2016-11-23 16:06 UTC by juliakimchung

click events, keypress events

2016-11-24 01:07 UTC, nathantbaker requested changes
added some notes! it needs some cleaning up before we merge, especially the model.js part. you won't want to push up any changes on that file so we don't run into two people editing the same thing

2016-11-24 01:07 UTC, nathantbaker commented on js/controller.js
> +module.exports = {activateEvents};
You shouldn't need a module.exports because other modules won't need to access this module's functions. You'll just call functions based on what's required at the top as needed. So you can delete line 99

2016-11-24 01:07 UTC, nathantbaker commented on js/model.js
>  // write functions that are called based on inputs in controller. They use view,
You shouldn't change anything in model.js. Ben will be pushing up code for this module, so we don't want to push up things and cause merge conflicts. If you need to test anything, it'd write test functions and console logs directly in the controller module. I'd recommend removing model.js from your pull request and we can keep code streams from being crossed :)

2016-11-24 01:07 UTC, nathantbaker commented on js/controller.js
> +		console.log("event",event );
If you do a console.log for all these function to say something like "You clicked the login button" do they all work? I was having trouble testing in this way.

2016-11-24 01:07 UTC, nathantbaker commented on index.html
> -      <!-- Search -->
We can't remove these sections of html, because this will be sections of html we will hide or show based on user inputs. Instead of a user being send to another page, we are just hiding and showing different sections of html to trick the user into thinking they are on a different page.

Same situation will all sections like this. Mind adding these back?

2016-11-24 01:07 UTC, nathantbaker commented on index.html
> +       Search:<input type="text" id = "nav-Search" class="form-control" placeholder="Text input">
I don't know if this affects how the html is rendered but I'd remove the space before and afer the equal sign in snippets of code such as `id = "nav-Search"`

2016-11-24 01:07 UTC, nathantbaker commented on index.html
> -                  <input id="nav-Search" type="text" class="form-control" placeholder="Find New Movies">
Rather than deleting the nav, try just putting `id="nav-Search"` or whatever id you want to use in this input tag rather than creating a new search bar, and the id will listen in on the element you want.

We need to keep the navbar so it's easy for users to know what to click, etc.

2016-11-24 03:00 UTC, juliakimchung commented on js/controller.js
> +		console.log("event",event );
yes! I saw them all work as event click , keypress button

2016-11-24 03:02 UTC, juliakimchung commented on js/controller.js
> +module.exports = {activateEvents};
got it...missed that one

2016-11-24 03:04 UTC, juliakimchung commented on js/model.js
>  // write functions that are called based on inputs in controller. They use view,
oh my bad..I wasn't going to change any on model.js, it was supposed to be just for the sake of testing. I'll delete them all since I know it works

2016-11-24 03:05 UTC, juliakimchung commented on index.html
> +       Search:<input type="text" id = "nav-Search" class="form-control" placeholder="Text input">
got it

2016-11-24 03:07 UTC, juliakimchung commented on index.html
> -                  <input id="nav-Search" type="text" class="form-control" placeholder="Find New Movies">
I'll need help on html

2016-11-24 03:18 UTC, nathantbaker commented on index.html
> -                  <input id="nav-Search" type="text" class="form-control" placeholder="Find New Movies">
ok i can help. get as far as you can, and I'll help polish the html with you sunday!

2016-11-24 03:27 UTC, juliakimchung commented on js/controller.js
> +		console.log("event",event );
this is what i see after clicking one of the event button. all works as below on console.log//
you clicked event button j…y.Event {originalEvent: MouseEvent, type: "click", target: a#nav-LogIn.hide-out, currentTarget: a#nav-LogIn.hide-out, relatedTarget: null…}

2016-11-24 03:44 UTC, juliakimchung commented on index.html
> -      <!-- Search -->
When I tried to import bootstrap, it got really crowded with too many commented out codes and I got confused in the mist of it. I was trying to make sense of the bootstrap code and I think that's when it got all deleted

2016-11-24 03:57 UTC, nathantbaker commented on index.html
> -      <!-- Search -->
gotcha. when using bootstrap code or when importing bootstrap? bootstrap is already pulling in so you don't need to import it again. It's an import in the sass/style.scss file, and if you're running webpack-dev-server, css is built on the fly. i'll take a look at your last commit!

2016-11-24 04:09 UTC, juliakimchung commented on index.html
> -      <!-- Search -->
do i need to push the model.js that I have cleaned up too? I deleted all the extra code I wrote for testing and made it look just like yesterday when I first pulled.

2016-11-24 04:11 UTC, juliakimchung commented on index.html
> -      <!-- Search -->
oh i was just copying some codes from bottstrap...is that right?

2016-11-24 04:37 UTC, juliakimchung commented on index.html
> -                  <input id="nav-Search" type="text" class="form-control" placeholder="Find New Movies">
Thanks! just made another commit on the updated html...retrieved accidentally deleted <search> section:)

2016-11-28 01:48 UTC, nathantbaker commented
closing this one. changed were added to branch `jk-controller`

2016-11-28 01:48 UTC, closed without merging